### ISSUE TITLE
assign = FALSE on datashield.login does not create a R session

### ISSUE THREAD

**Issue by ESCRI11** [datashield/DSI#8]
On previous versions, the following code

```
library('DSI')
library('DSOpal')
require('dsBaseClient')
builder <- DSI::newDSLoginBuilder()
builder$append(server = "study1",
               url = "https://opal-demo.obiba.org/",
               user = "dsuser", password = "password", driver = "OpalDriver")
logindata <- builder$build()
connections <- DSI::datashield.login(logins = logindata) # assign = FALSE is default
```

Would create a R session on the Opal, to later assign tables/resources.

On the latest release it does not create it, so when assigning using `datashield.assign.expr` the client is not found

```
$Study1
[1] "[Client error: (404) Not Found]"
```

Should I change my workflow or this is a bug of the new release?

Thanks for the attention.

**Comment by StuartWheater** [comment]
Please could you specify the versions of Opal, DSI, DSOpal and opalr you have installed.

Stuart

**Comment by ESCRI11** [comment]
Opal 4.0.2
DSI 1.2.0
DSOpal 1.2.0
opalr 2.0.0

**Comment by ymarcon** [comment]
I can reproduce, and it is an opalr issue.

**Comment by ESCRI11** [comment]
Sorry about that. Should I move the issue to the opalr repository?

**Comment by ymarcon** [comment]
The problem was in DSOpal instead, and has always been. The `dsAssignExpr` implementation was not ensuring that the DataSHIELD R sessions were created, like the `dsAssignTable` and `dsAssignResource` do. This means that this issue only happen if this is the first datashield function call: if you call `datashield.assign.table()` or `datashield.assign.resource()` or `datashield.symbols()` prior to `datashield.assign.expr()` there will be no problem.

The fix will be available in the next DSOpal release, or install with `remotes::install_github("datashield/DSOpal")`.
